import 'bootstrap/dist/css/bootstrap.css'
import Navbar from './components/navbar'
import TanstackProvider from './providers/tanstackProvider'
import "./globals.css"
import NextAuthProvider from './providers/sessionProvider'
import SideNavBar from './components/sideNavBar'
import { Providers } from './providers'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
      <NextAuthProvider>
        <TanstackProvider>
          <Providers>
            <Navbar/>
              <SideNavBar/>
              <div className='main'>
                {children}
              </div>
          </Providers>
        </TanstackProvider>
      </NextAuthProvider>
      </body>
    </html>
  )
}
