import 'bootstrap/dist/css/bootstrap.css'
import Navbar from './components/navbar'
import TanstackProvider from './providers/tanstackProvider'
import "./globals.css"
import NextAuthProvider from './providers/sessionProvider'
import SideNavBar from './components/sideNavBar'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
      <NextAuthProvider>
        <TanstackProvider>
          <Navbar/>
            <SideNavBar/>
            <div className='main'>
              {children}
            </div>
        </TanstackProvider>
      </NextAuthProvider>
      </body>
    </html>
  )
}
